version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: .
      dockerfile: ./dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html
    env_file:
      - ./env/mysql.env

  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/artisan.dockerfile
    volumes:
      - ./src:/var/www/html
  npm:
    build:
      context: .
      dockerfile: ./dockerfiles/npm.dockerfile
    volumes:
      - ./src:/var/www/html
